#!/usr/bin/env python3
"""Collect the code blocks of a tutorial marked for CI into one script and run it.

Blocks are marked with the `ci` class in the fence attributes:

    ```{.bash .ci}                         run with bash
    ```{.python .ci}                       run with python3
    ```{.cpp .ci file="src/Test.cxx"}      write to src/Test.cxx (any language)

The blocks are collected in the order a learner goes through the tutorial
(learners/setup.md, episodes/*.md, then the other learners/*.md pages) into
<work directory>/tutorial.sh, which is then run in the work directory.
It fails if a block fails or ROOT prints an error ("Error in <...>").

Usage: run_blocks.py <tutorial directory> <work directory>
"""
import re
import shlex
import subprocess
import sys
import textwrap
from pathlib import Path

FENCE = re.compile(r"^([ \t]*)```\{([^}]*)\}[ \t]*\n(.*?)^[ \t]*```", re.S | re.M)
END = "CI_BLOCK_END"


def marked_blocks(markdown):
    """Yield (line number, classes, file name, code) for each block with the ci class."""
    text = markdown.read_text()
    for match in FENCE.finditer(text):
        attributes = match.group(2)
        classes = re.findall(r"\.([\w+-]+)", attributes)
        if "ci" not in classes:
            continue
        file_name = re.search(r'file="([^"]+)"', attributes)
        line = text.count("\n", 0, match.start()) + 1
        yield line, classes, file_name and file_name.group(1), textwrap.dedent(match.group(3))


def script(directory):
    """Return the tutorial as one bash script."""
    learners = directory / "learners"
    setup = learners / "setup.md"
    sources = [setup] + sorted((directory / "episodes").glob("*.md")) + sorted(set(learners.glob("*.md")) - {setup})
    lines = [
        "#!/bin/bash",
        f"# Code blocks marked for CI in {directory.name}, generated by run_blocks.py",
        "set -e",
    ]
    for markdown in filter(Path.exists, sources):
        for line, classes, file_name, code in marked_blocks(markdown):
            location = markdown.relative_to(directory)
            lines += ["", f'echo "=== {location}:{line}"']
            if file_name:
                quoted = shlex.quote(file_name)
                lines += [f"mkdir -p $(dirname {quoted})", f"cat > {quoted} <<'{END}'", code.rstrip("\n"), END]
            elif "python" in classes:
                lines += [f"python3 - <<'{END}'", code.rstrip("\n"), END]
            elif "bash" in classes:
                lines.append(code.rstrip("\n"))
            else:
                raise SystemExit(f"{location}:{line}: ci block needs .bash, .python or file=")
    return "\n".join(lines) + "\n"


def main(directory, work):
    work.mkdir(parents=True, exist_ok=True)
    (work / "tutorial.sh").write_text(script(directory))
    process = subprocess.Popen(["bash", "tutorial.sh"], cwd=work, stdin=subprocess.DEVNULL,
                               stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    location = "tutorial.sh,line=1"
    root_errors = 0
    for line in process.stdout:
        print(line, end="", flush=True)
        if line.startswith("=== "):
            location = line[4:].strip().replace(":", ",line=")
        elif line.startswith("Error in <"):
            root_errors += 1
            print(f"::error file={location}::{line.strip()}")
    if process.wait() != 0:
        print(f"::error file={location}::block failed")
    return 1 if process.returncode or root_errors else 0


if __name__ == "__main__":
    sys.exit(main(Path(sys.argv[1]), Path(sys.argv[2]).resolve()))
